services:
  server:
    image: fogfl:local
    container_name: server
    ports:
      - "8181:8181"
    networks:
      fogfl_network:
        ipv4_address: 172.18.0.2

  client_0:
    image: fogfl:local
    container_name: client_0
    networks:
      fogfl_network:
        ipv4_address: 172.18.0.3
    depends_on:
      - server

  client_1:
    image: fogfl:local
    container_name: client_1
    networks:
      fogfl_network:
        ipv4_address: 172.18.0.4
    depends_on:
      - server

networks:
  fogfl_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
